# Generated by Django 6.0.3 on 2026-04-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('foodType', models.CharField(max_length=100)),
                ('location_text', models.CharField(max_length=255)),
                ('priceRange', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodtruck')),
            ],
        ),
    ]
