# Generated by Django 6.0.3 on 2026-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foodtruck_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_truck_images/'),
        ),
    ]
