# Generated by Django 6.0.3 on 2026-04-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_foodtruck_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_truck_gallery_images/')),
                ('food_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='app.foodtruck')),
            ],
        ),
    ]
