# Generated by Django 6.0.3 on 2026-04-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foodtruckimagegallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='location',
        ),
        migrations.AlterField(
            model_name='foodtruckimagegallery',
            name='food_truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app.foodtruck'),
        ),
    ]
