# Generated by Django 6.0.3 on 2026-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_foodtruck_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='location',
            field=models.CharField(default='TBD', max_length=200),
            preserve_default=False,
        ),
    ]
