# Generated by Django 6.0.3 on 2026-04-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_foodtruck_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='description',
            field=models.CharField(default='this is a test description for the food trucks. hmmm yes very yummy. you should eat here because this food comes frmo a truck. that is why this is a fodo truck. oh yes. oh yeah.', max_length=1000),
            preserve_default=False,
        ),
    ]
