# Generated by Django 6.0.3 on 2026-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_foodtruck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='phoneNumber',
            field=models.CharField(default='123-456-7890', max_length=15),
            preserve_default=False,
        ),
    ]
