# Generated by Django 6.0.3 on 2026-04-21 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_foodtruck_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='dietaryRestrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[''], size=5),
            preserve_default=False,
        ),
    ]
