# Generated by Django 6.0.3 on 2026-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_foodtruck_dietaryrestrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='popularity',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
