# Generated by Django 6.0.3 on 2026-04-21 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_foodtruck_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='priceRangeArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[5, 10], size=2),
            preserve_default=False,
        ),
    ]
