# Generated by Django 6.0.3 on 2026-04-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_foodtruck_pricerangearray'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='priceRange',
        ),
    ]
