# Generated by Django 6.0.3 on 2026-04-22 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_foodtruck_pricerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='priceRangeArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=2),
        ),
    ]
