# Generated by Django 6.0.3 on 2026-04-23 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_foodtruck_pricerangearray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='dietaryRestrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=5),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
